# ======================================
# Printing Numbers 
# ======================================

# ====================================== 
# Random Numbers in Ascending Order 
# ======================================
"""
Problem:
Print numbers in ascending order from a number, A to limit, B.

Mathematical Principle:
The sequence of numbers from A to B is an 
arithmetic sequence with a common difference of d.

Pseudocode:
1. Initialize a counter to A.
2. Repeat the following steps until the counter reaches limit, B:
   a. Print the current value of the counter.
   b. Increase the counter by d.
"""

A = int(input("Enter the starting number: "))
B = int(input("Enter the limit number, B: "))
d = int(input("Enter the common difference, d: "))

for number in range(A, B + 1, d):
    print(number)



# ====================================== 
# Random Numbers in Descending Order
# ======================================
"""
Problem:
Print numbers in descending order of any given range (B to A).

Mathematical Principle:
The sequence of numbers from B to A is an 
arithmetic sequence with a common difference of d.

where d is negative.

Pseudocode:
1. Initialize a counter to B.
2. Repeat the following steps until the counter reaches A:
   a. Print the current value of the counter.
   b. Decrease the counter by d (d is negative).
"""
B = int(input("Enter the starting, B: "))
A = int(input("Enter the limit number, A: "))
d = int(input("Enter the common difference, d: "))


for number in range(B + 1, A, d):
    print(number)
    
# ====================================== 
# Specific Sequences 
# ======================================

# === 1. Numbers from 1 to 100 ===

print("Numbers from 1 to 100:\n ")

for number in range(1, 101):
    print(number )

# Alternatively

count = 1

for x in range(100):
    print(count)
    count += 1

    
# ======================================
# Even & Odd Numbers
# ======================================

# === Even Numbers ====
"""
Problem:
Print even numbers within a specified range (A -> B).

Mathematical Principle:
An even number is an integer that is exactly divisible by 2.
The sequence of even numbers can be generated by starting 
from the first even number and incrementing by 2.

Pseudocode:
1. Initialize a counter to 1.
2. Repeat the following steps until the counter reaches 100:
   a. Print the current value of the counter.
   b. Increment the counter by 1.
"""

for number in range(1, 101):
    if number % 2 == 0:
        print(number)
        

# Alternatively

for i in range(0, 101, 2):
    print(i)

    
# === Odd Numbers ====

for number in range(1, 51):
    if number % 2 != 0:
        print(number)
    
    # Alternatively

for i in range(1, 101, 2):
    print(i)
    
    
# ==== Combining both ===

for x in range(1, 51):
    if x % 2 == 0:
        print(f"{x} is even.") 
    else:
        print(f"{x} is odd.")
        
